ProjectEvaluationSystem/urls.py
from django.conf.urls.static import static
from django.conf.urls import include
from django.conf import settings
from django.contrib import admin
from django.urls import path
# -----------------------------------------------------------------------------------------------------------------------------------

urlpatterns = [
    path('', include('main.urls.urls', namespace = 'main')),
    path('admin/', admin.site.urls),
    path('master-data/', include('main.urls.master_data', namespace = 'master_data')),
]
urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

main/urls/urls.py
from main.views import base_views, communicationviews, evaluationviews
from django.urls import path

# -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

app_name = 'main'
urlpatterns = [
    path('', base_views.index_page, name = 'index_page'),
    # sign in path <----------------------------------------------->
    path('signin/', base_views.signin_page, name ='sign_page'),
    path('ajax-signin/', base_views.signin, name = 'ajax_signin'),
    path('signup/', base_views.signup_page , name ='signup_page'),
    path('ajax-signup/', base_views.signup, name = 'ajax_signup'),
    # sign out path <----------------------------------------------->
    path('signout/', base_views.signout, name = 'sign_out_page'),
    # forget password path <----------------------------------------------->
    path('forget-password/', base_views.forget_password_page, name = 'forget_password_page'),
    path('ajax/forget-password/send-validation-code/', base_views.forget_password_send_validation_code, name = 'ajax_forget_password_send_validation_code'),
    path('ajax/forget-password/change-password/', base_views.forget_password_change_password, name = 'ajax_forget_password_change_password'),
    # organization --------------------------------------------------------------
    path('official-letter/', communicationviews.communication_list_page, name = 'communication_list_page'),
    path('official-letter/details-<int:pk>/', communicationviews.official_letter_details_page, name = 'official_letter_details_page'),
    path('official-letter/create/', communicationviews.communication_create_page, name = 'communication_create_page'),
    path('ajax/official-letter/create/', communicationviews.create_official_letter, name = 'ajax_create_official_letter'),
    path('ajax/official-letter/answer/', communicationviews.answer_official_letter, name = 'ajax_answer_official_letter'),
    # evaluation --------------------------------------------------------------
    path('evaluation/user/<int:project_id>/', evaluationviews.evaluation_user_page, name = 'evaluation_user_page'),
    path('ajax/evaluation/user/', evaluationviews.project_evaluation_user, name = 'ajax_project_evaluation_user'),
    path('evaluation/assistant/<int:project_id>/', evaluationviews.evaluation_assistant_page, name = 'evaluation_assistant_page'),
    path('ajax/evaluation/assistant/', evaluationviews.project_evaluation_assistant, name = 'ajax_project_evaluation_assistant'),
]

main/models.py
from django.contrib.auth.base_user import BaseUserManager, AbstractBaseUser
from django.utils.deconstruct import deconstructible
from django.db.models import JSONField
from django.utils import timezone
import random, string, datetime
from django.db import models

# ------------------------------------------------------------------------------------------------------------------------------------

@deconstructible
class default_history_field():
    def __call__(self):
        return {'list': []}


@deconstructible
class default_similar_projects_field():
    def __call__(self):
        return {'completed': 0, 'not_completed': 0}


@deconstructible
class default_requires_field():
    def __call__(self):
        return {'status': False, 'description': None}


@deconstructible
class default_answer_field():
    def __call__(self):
        return {'description': None, 'datetime': None, 'file': None}


@deconstructible
class default_evaluation_user_field():
    def __call__(self):
        return {"rationale_studies": { "item": None, "file": None, "point": None },\
            "comprehensive_target_needs": { "item": None, "point": None },\
            "comprehensive_necessity_of_purpose": { "item": None, "point": None },\
            "project_implementation_time": { "item": None, "point": None },\
            "repetition_rate": { "item": None, "point": None }, "abundance_rate":\
            { "item": None, "point": None }, "population": { "item": None,\
            "sub_item": None, "point": None }, "type_of_project": { "item": None, "point": None }}


@deconstructible
class create_validation_code():
    def __init__(self, size):
        self.size = size

    def __call__(self):
        code = ''.join(random.choice(string.digits) for i in range(self.size))
        return code

# --------------------------------------------------------------------------------------------------------------------------------------

# Validation (اعتبار سنجی) Model   
class Validation(models.Model):
    mobile = models.CharField(verbose_name = 'شماره موبایل', max_length = 11, unique = True)
    validation_code = models.CharField(verbose_name = 'کد فعال سازی', max_length = 6, default = create_validation_code(6))
    createdatetime = models.DateTimeField(verbose_name = 'تاریخ و زمان ایجاد', auto_now_add = True)

# --------------------------------------------------------------------------------------------------------------------------------------

class UserManager(BaseUserManager):
    def create_user(self, username, first_name, last_name, father_s_name, birth_certificate_id, national_code, password, **kwargs):
        if not username:
            raise ValueError("Users must have username")
        if not first_name:
            raise ValueError("Users must have first name")
        if not last_name:
            raise ValueError("Users must have last name")
        if not father_s_name:
            raise ValueError("Users must have fathers name")
        if not birth_certificate_id:
            raise ValueError("Users must have birth certificate id")
        if not national_code:
            raise ValueError("Users must have national_code")
        if not password:
            raise ValueError("Users must have password")

        user = self.model(username = username, **kwargs)
        user.first_name = first_name
        user.last_name = last_name
        user.father_s_name = father_s_name
        user.birth_certificate_id = birth_certificate_id
        user.national_code = national_code
        user.set_password(password)
        user.save()
        return user

    def create_staffuser(self, username, first_name, last_name, father_s_name, birth_certificate_id, national_code, password, **kwargs):
        user = self.model(username = username, staff = True, **kwargs)
        user.first_name = first_name
        user.last_name = last_name
        user.father_s_name = father_s_name
        user.birth_certificate_id = birth_certificate_id
        user.national_code = national_code
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, username, first_name, last_name, father_s_name, birth_certificate_id, national_code, password, **kwargs):
        user = self.model(username = username, staff = True, superuser = True, **kwargs)
        user.first_name = first_name
        user.last_name = last_name
        user.father_s_name = father_s_name
        user.birth_certificate_id = birth_certificate_id
        user.national_code = national_code
        user.set_password(password)
        user.save()
        return user

# --------------------------------------------------------------------------------------------------------------------------------------

# User (کاربر) Model
class User(AbstractBaseUser):
    # Personal Information
    first_name = models.CharField(verbose_name = 'first name', max_length = 50, db_index = True)
    last_name = models.CharField(verbose_name = 'last name', max_length = 150, db_index = True)
    father_s_name = models.CharField(verbose_name = 'fathers name', max_length = 50, db_index = True)
    GENDER_STATUS = (
        ('f', 'زن'),
        ('m', 'مزد')
    )
    gender = models.CharField(verbose_name = 'جنسیت', max_length = 1, choices = GENDER_STATUS, null = True)
    birth_certificate_id = models.CharField(verbose_name = 'birth certificate id', max_length = 10, unique = True, db_index = True)
    national_code = models.CharField(verbose_name = 'national code', max_length = 10, unique = True, db_index = True)
    birthday = models.DateField(verbose_name = 'تاریخ تولد', null = True)
    issue_place = models.CharField(verbose_name = 'issue place', max_length = 50)
    # Educational Information
    DEGREE_TYPE = (
        ('elementary', 'ابتدایی'),
        ('middle-school', 'سیکل'),
        ('diploma', 'دیپلم'),
        ('associate', 'فوق دیپلم'),
        ('bachelor', 'لیسانس'),
        ('master', 'فوق لیسانس'),
        ('phd', 'دکترا'),
        ('post-doctoral', 'فوق دکترا'),
    )
    degree = models.CharField(verbose_name = 'مقطع تحصیلی', max_length = 13, choices = DEGREE_TYPE, null = True)
    major = models.CharField(verbose_name = 'رشته تحصیلی', max_length = 255, null = True)
    university_of_study = models.CharField(verbose_name = 'دانشگاه محل تحصیل', max_length = 255, null = True)
    # Working information
    executive_device = models.CharField(verbose_name = 'دستگاه اجرایی', max_length = 255, null = True)
    role = models.CharField(verbose_name = 'سمت', max_length = 50, db_index = True, null = True)
    work_experience = models.TextField(verbose_name = 'سابقه کاری', null = True)
    personnel_id = models.CharField(verbose_name = 'شماره پرسنلی', max_length = 50, db_index = True, null = True)
    # Access information
    address = models.TextField(verbose_name = 'آدرس', null = True)
    zip_code = models.CharField(verbose_name = 'کدپستی', max_length = 10, null = True)
    mobile = models.CharField(verbose_name = 'شماره موبایل', max_length = 11, db_index = True, null = True)
    necessary_contact_number = models.CharField(verbose_name = 'شماره تماس ضروری', max_length = 11, null = True)
    workplace_number = models.CharField(verbose_name = 'شماره محل کار', max_length = 11, null = True)
    email = models.EmailField(verbose_name = 'ایمیل', null = True)
    # Profile information
    username = models.CharField(verbose_name = 'username', max_length = 50, db_index = True, unique = True)
    profile = models.ImageField(verbose_name = 'پروفایل', upload_to = 'media/images/user/profile/', default = 'static/images/default/default-profile.jpg')
    ACCESS_GROUP = (
        ('user','کاربر'),
        ('department_of_administration','ریاست اداره'),
        ('deputy_for_planning_and_civil_affairs','معاونت امور برنامه ریزی و عمرانی'),
        ('governor','فرماندار')
    )
    access_group = models.CharField(verbose_name = 'گروه دسترسی', max_length = 37, choices = ACCESS_GROUP, blank = True, null = True)
    # Attachments
    picture = models.ImageField(verbose_name = 'عکس', upload_to = 'media/images/user/picture/', blank = True, null = True)
    personal_id_card = models.ImageField(verbose_name = 'کارت شناسایی پرسنلی', upload_to = 'media/images/user/personal_id_card/', blank = True, null = True)
    device_introduction_letter = models.FileField(verbose_name = 'معرفی نامه دستگاه', upload_to = 'media/files/user/device_introduction_letter/', blank = True, null = True)
    sample_signature = models.ImageField(verbose_name = 'نمونه امضا', upload_to = 'media/images/user/signature/', blank = True, null = True)
    # Base information
    superuser = models.BooleanField(verbose_name = 'وضعیت مدیریت', default = False)
    staff = models.BooleanField(verbose_name = 'وضعیت کارمند', default = False)
    active = models.BooleanField(verbose_name = 'وضعیت فعالیت', default = True)
    history = JSONField(verbose_name = 'تاریخچه', default = default_history_field())
    create_date = models.DateTimeField(verbose_name = 'تاریخ ثبت کاربر', auto_now_add = True)
    update_date = models.DateTimeField(verbose_name = 'تاریخ بروزرسانی کاربر', auto_now = True)

    USERNAME_FIELD = 'username'

    REQUIRED_FIELDS = ['first_name', 'last_name', 'father_s_name', 'birth_certificate_id', 'national_code']

    objects = UserManager()

    @property
    def is_active(self):
        return self.active

    @property
    def is_superuser(self):
        return self.superuser

    @property
    def is_staff(self):
        return self.staff

    @property
    def is_governor(self):
        if self.access_group == 'governor':
            return True
        else:
            return False
    
    @property
    def is_deputy(self):
        if self.access_group == 'deputy_for_planning_and_civil_affairs':
            return True
        else:
            return False

    def get_access_group(self):
        try:
            group = {
                'user': 'کاربر',

templates/parents/footer.html
{% load i18n static %}

<footer class="footer text-center">
    <div class="container">
      <div class="row">
        <div class="col-12">
          تمام حقوق این اثر متعلق به این سایت می باشد. &copy; 2021
        </div>
      </div>
    </div>
  </footer>

  
  <!-- <script src="{% static "vendor/js/jquery4.min.js" %}" type="text/javascript" ></script> -->
  <script src="{% static "js/jquery/jquery-3.5.1.min.js" %}" type="text/javascript"></script>
  <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script> -->
  <script src="{% static "js/popper/popper.min.js" %}" type="text/javascript"></script>
  <script src="{% static "js/bootstrap/bootstrap.min.js" %}" type="text/javascript"></script>
  <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script> -->
  <!-- <script src="{% static "js/datatables/vendor.min.js" %}" type="text/javascript"></script> -->

      <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
      <!-- <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script> -->
      <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script> -->
  
      <!-- Option 2: jQuery, Popper.js, and Bootstrap JS -->
      <!-- <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script> -->
      <!-- <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script> -->
      <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script> -->
     

  <script src="{% static "js/datatables/jquery.dataTables.min.js" %}" type="text/javascript"></script>
  <script src="{% static "js/datatables/dataTables.bootstrap4.min.js" %}" type="text/javascript"></script>
  <script src="{% static "js/datatables/dataTables.responsive.min.js" %}" type="text/javascript"></script>
  <script src="{% static "js/datatables/responsive.bootstrap4.min.js" %}" type="text/javascript"></script>
  <script src="{% static "js/datatables/dataTables.buttons.min.js" %}" type="text/javascript"></script>
  <script src="{% static "js/datatables/buttons.bootstrap4.min.js" %}" type="text/javascript"></script>
  <script src="{% static "js/jszip.min.js" %}" type="text/javascript"></script>
  <script src="{% static "js/datatables/buttons.html5.min.js" %}" type="text/javascript"></script>
  <script src="{% static "js/datatables/buttons.flash.min.js" %}" type="text/javascript"></script>
  <script src="{% static "js/datatables/buttons.print.min.js" %}" type="text/javascript"></script>
  <script src="{% static "js/datatables/dataTables.keyTable.min.js" %}" type="text/javascript"></script>
  <script src="{% static "js/datatables/dataTables.select.min.js" %}" type="text/javascript"></script>
  <script src="{% static "js/datatables/datatables.init.js" %}" type="text/javascript"></script>
  <!-- <script src="{% static "js/datatables/app.min.js" %}" type="text/javascript"></script> -->

  <script src="{% static "js/select2/select2.min.js" %}" type="text/javascript"></script>
  <!-- <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js" type="text/javascript"></script> -->

  <script src="{% static "js/main.js" %}" type="text/javascript"></script>

templates/parents/head.html
{% load i18n static %}

<!DOCTYPE html>
<html lang="fa">
<head>
    <meta charset="UTF-8" >
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- third party css -->
    <link href="{% static "js/datatables/dataTables.bootstrap4.min.css" %}" rel="stylesheet" type="text/css" />
    <link href="{% static "js/datatables/responsive.bootstrap4.min.css" %}" rel="stylesheet" type="text/css" />
    <link href="{% static "js/datatables/buttons.bootstrap4.min.css" %}" rel="stylesheet" type="text/css" />
    <link href="{% static "js/datatables/select.bootstrap4.min.css" %}" rel="stylesheet" type="text/css" />

    <!-- App css -->
    <link href="{% static "css/css/bootstrap.min.css" %}" rel="stylesheet" type="text/css" />
    <link href="{% static "css/css/icons.min.css" %}" rel="stylesheet" type="text/css" />
    <!-- <link href="{% static "css/css/app.min.css" %}" rel="stylesheet" type="text/css" /> -->
    <link rel="stylesheet" href="{% static "css/style.min.css" %}">
    
    <link rel="icon" href="{% static "images/favicon.ico" %}"/>
    
    <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script> -->
    <!-- <script type="text/javascript" src="https://code.jquery.com/jquery-3.5.1.min.js"></script> -->
    <script src="{% static "js/jquery/jquery-3.5.1.min.js" %}" type="text/javascript"></script>
    <script src="{% static "js/kamadatepicker.js" %}" type="text/javascript"></script>
    <!-- <script src="{% static "js/popper/popper.min.js" %}" type="text/javascript"></script> -->
    <!-- <script src="{% static "js/bootstrap/bootstrap.min.js" %}" type="text/javascript"></script> -->
    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous"> -->
    <!-- <script src="{% static "js/responsive-table/dataTables.responsive.min.js" %}" type="text/javascript"></script> -->
    <!-- <script src="{% static "js/main.js" %}" type="text/javascript"></script> -->

templates/parents/header.html
{% load i18n static %}

<header>
    <div class="container-fluid">
        <div class="row justify-content-between">
            <div class="col-7">
                <div class="logo right-logo">
                    <a href="{{BASE_URL}}/"><img src="{% static "images/left-logo.png" %}" alt="لوگوی سیستم"></a>
                    <h1>سامانه بررسی پروژه ها</h1>
                </div>
            </div>
            
            <div class="col-3">
                <div class="logo left-logo">
                    
                </div>
            </div>
        </div>
    </div>
</header>
<div class="container-fluid">
    <div class="top-menu">
        <div class="row">
            <div class="col-12 d-flex justify-content-between">
                <div class="right-part">
                    <a href="{% url 'main:index_page' %}" class="home"><i class="fas fa-home"></i></a>
                    <span class="cursor-pointer history-back mr-3"><i class="far fa-long-arrow-right"></i> بازگشت</span>
                </div>
                {% if user.is_authenticated %}
                    <a href="{% url 'main:sign_out_page' %}">خروج <i class="fas fa-sign-out"></i></a>
                {% endif %}
            </div>
        </div>
    </div>
</div>
<script>
    $(".history-back").click(function () {
        history.back();
    })
</script>

templates/parents/sidebar.html
{% load i18n static %}

<div class="col-3">
    <div class="profile">
        <img src="{% static "images/profile-pin.jpg" %}">
        <div class="profile-content">
            <div class="avatar my-2">
                <img src="/{{request.user.profile}}" alt="عکس پروفایل" width="60" height="60">
            </div>
            <div class="information">
                <div class="bio">
                    <span>نام و نام خانوادگی : </span>
                    <span>{{request.user.get_fullname}}</span>
                    <br>
                    <span>نقش : </span>
                    <span>{{request.user.get_access_group_display}}</span>
                </div>
                <div class="company">
                    <span> </span>
                    <span></span>
                </div>
                <div class="role">
                    <span> </span>
                    <span></span>
                </div>
            </div>
            <div class="date mt-3"></div>
        </div>
    </div>
    <div class="side-menu text-right">
        <div class="menu-item">
            <div class="menu-item-title d-flex">
                <div class="item-part collapse-part">
                    <i class="far fa-plus"></i>
                </div>
                <div class="item-part item-title">
                    <i class="fas fa-user-chart"></i>
                    منوی کاربری
                </div>
            </div>
            <div class="menu-item-subset">

                <div class="menu-item-subset-single">
                    <a href="{% url 'master_data:personnel_details_page' request.user.username %}">
                        <div class="d-flex">
                            <div class="sub-item-part indent-part"></div>
                            <div class="sub-item-part item-option">
                                <i class="fas fa-circle"></i>
                                    مشاهده پروفایل
                            </div>
                        </div>
                    </a>
                </div>

                <div class="menu-item-subset-single">
                    <a href="{% url 'master_data:personnel_edit_page' request.user.username %}">
                        <div class="d-flex">
                            <div class="sub-item-part indent-part"></div>
                            <div class="sub-item-part item-option">
                                <i class="fas fa-circle"></i>
                                    ویرایش پروفایل
                            </div>
                        </div>
                    </a>
                </div>


                <div class="menu-item-subset-single">
                    <a href="{% url 'main:communication_create_page' %}">
                        <div class="d-flex">
                            <div class="sub-item-part indent-part"></div>
                            <div class="sub-item-part item-option">
                                <i class="fas fa-circle"></i>
                                     ثبت نامه مکاتباتی
                            </div>
                        </div>
                    </a>
                </div>

                <div class="menu-item-subset-single">
                    <a href="{% url 'main:communication_list_page' %}">
                        <div class="d-flex">
                            <div class="sub-item-part indent-part"></div>
                            <div class="sub-item-part item-option">
                                <i class="fas fa-circle"></i>
                                     لیست مکاتبات من
                            </div>
                        </div>
                    </a>
                </div>
<!-- 
                <div class="menu-item-subset-single">
                    <a href="{.% url 'master_data:deputy_list_page' %}">
                        <div class="d-flex">
                            <div class="sub-item-part indent-part"></div>
                            <div class="sub-item-part item-option">
                                <i class="fas fa-circle"></i>
                                    مشاهده پروفایل دستگاه اجرایی
                            </div>
                        </div>
                    </a>
                </div>

                <div class="menu-item-subset-single">
                    <a href="{.% url 'master_data:deputy_list_page' %}">
                        <div class="d-flex">
                            <div class="sub-item-part indent-part"></div>
                            <div class="sub-item-part item-option">
                                <i class="fas fa-circle"></i>
                                    ویرایش پروفایل دستگاه اجرایی
                            </div>
                        </div>
                    </a>
                </div> -->



            </div>
        </div>

        <div class="menu-item">
            <div class="menu-item-title d-flex">
                <div class="item-part collapse-part">
                    <i class="far fa-plus"></i>
                </div>
                <div class="item-part item-title">
                    <i class="fas fa-user-chart"></i>
                    پروژه ها
                </div>
            </div>
            <div class="menu-item-subset">
                <div class="menu-item-subset-single">
                    <a href="{% url 'master_data:project_create_page' %}">
                        <div class="d-flex">
                            <div class="sub-item-part indent-part"></div>
                            <div class="sub-item-part item-option">
                                <i class="fas fa-circle"></i>
                                ثبت پروژه
                            </div>
                        </div>
                    </a>
                </div>

                <div class="menu-item-subset-single">
                    <a href="{% url 'master_data:project_list_page' %}">
                        <div class="d-flex">
                            <div class="sub-item-part indent-part"></div>
                            <div class="sub-item-part item-option">
                                <i class="fas fa-circle"></i>
                                لیست پروژه ها
                            </div>
                        </div>
                    </a>
                </div>
                <div class="menu-item-subset-single">
                    <a href="{% url 'master_data:project_list_all_page' %}">
                        <div class="d-flex">
                            <div class="sub-item-part indent-part"></div>
                            <div class="sub-item-part item-option">
                                <i class="fas fa-circle"></i>
                                لیست کل پروژه های سازمان
                            </div>
                        </div>
                    </a>
                </div>
            </div>
        </div>

        <div class="menu-item">
            <div class="menu-item-title d-flex">
                <div class="item-part collapse-part">
                    <i class="far fa-plus"></i>
                </div>
                <div class="item-part item-title">
                    <i class="fas fa-database"></i>
                    اطلاعات پایه
                </div>
            </div>
            <div class="menu-item-subset">
                <div class="menu-item-subset-single">
                    <a href="{% url 'master_data:personnel_list_page' %}">
                        <div class="d-flex">
                            <div class="sub-item-part indent-part"></div>
                            <div class="sub-item-part item-option">
                                <i class="fas fa-circle"></i>
                                فهرست پرسنلی
                            </div>
                        </div>
                    </a>
                </div>
                <div class="menu-item-subset-single">
                    <a href="{% url 'master_data:organization_list_page' %}">
                        <div class="d-flex">
                            <div class="sub-item-part indent-part"></div>
                            <div class="sub-item-part item-option">
                                <i class="fas fa-circle"></i>
                                     دستگاه اجرایی
                            </div>
                        </div>
                    </a>
                </div>
                <div class="menu-item-subset-single">
                    <a href="{% url 'master_data:projectstype_list_page' %}">
                        <div class="d-flex">
                            <div class="sub-item-part indent-part"></div>
                            <div class="sub-item-part item-option">
                                <i class="fas fa-circle"></i>
                                 نوع پروژه ها
                            </div>
                        </div>
                    </a>
                </div>
               
            </div>
        </div>
    </div>
</div>