ProjectEvaluationSystem/urls.py
from django.conf.urls.static import static
from django.conf.urls import include
from django.conf import settings
from django.contrib import admin
from django.urls import path
# -----------------------------------------------------------------------------------------------------------------------------------

urlpatterns = [
    path('', include('main.urls.urls', namespace = 'main')),
    path('admin/', admin.site.urls),
    path('master-data/', include('main.urls.master_data', namespace = 'master_data')),
]
urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

main/urls/urls.py
from main.views import base_views, communicationviews, evaluationviews
from django.urls import path

# -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

app_name = 'main'
urlpatterns = [
    path('', base_views.index_page, name = 'index_page'),
    # sign in path <----------------------------------------------->
    path('signin/', base_views.signin_page, name ='sign_page'),
    path('ajax-signin/', base_views.signin, name = 'ajax_signin'),
    path('signup/', base_views.signup_page , name ='signup_page'),
    path('ajax-signup/', base_views.signup, name = 'ajax_signup'),
    # sign out path <----------------------------------------------->
    path('signout/', base_views.signout, name = 'sign_out_page'),
    # forget password path <----------------------------------------------->
    path('forget-password/', base_views.forget_password_page, name = 'forget_password_page'),
    path('ajax/forget-password/send-validation-code/', base_views.forget_password_send_validation_code, name = 'ajax_forget_password_send_validation_code'),
    path('ajax/forget-password/change-password/', base_views.forget_password_change_password, name = 'ajax_forget_password_change_password'),
    # organization --------------------------------------------------------------
    path('official-letter/', communicationviews.communication_list_page, name = 'communication_list_page'),
    path('official-letter/details-<int:pk>/', communicationviews.official_letter_details_page, name = 'official_letter_details_page'),
    path('official-letter/create/', communicationviews.communication_create_page, name = 'communication_create_page'),
    path('ajax/official-letter/create/', communicationviews.create_official_letter, name = 'ajax_create_official_letter'),
    path('ajax/official-letter/answer/', communicationviews.answer_official_letter, name = 'ajax_answer_official_letter'),
    # evaluation --------------------------------------------------------------
    path('evaluation/user/<int:project_id>/', evaluationviews.evaluation_user_page, name = 'evaluation_user_page'),
    path('ajax/evaluation/user/', evaluationviews.project_evaluation_user, name = 'ajax_project_evaluation_user'),
    path('evaluation/assistant/<int:project_id>/', evaluationviews.evaluation_assistant_page, name = 'evaluation_assistant_page'),
    path('ajax/evaluation/assistant/', evaluationviews.project_evaluation_assistant, name = 'ajax_project_evaluation_assistant'),
]

main/views/base_views.py
from utils.base_fuction import is_valid_national_code, check_password, send_sms, calculate_time_difference
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.sessions.models import Session
from django.shortcuts import render, redirect
import datetime, json, random, string, re
from django.http import JsonResponse
from django.utils import timezone
from django.conf import settings
# get model
from main.models import User, Validation

# -------------------------------------------------------------------------------------------------------------------------------------

@login_required(login_url = 'main:sign_page')
def index_page(request):
    return render(request, 'main/index.html')


def signin_page(request):
    if not request.user.is_authenticated:
        return render(request, 'account/signin.html')
    else:
        return redirect('main:index_page')


def signup_page(request):
    if not request.user.is_authenticated:
        return render(request, 'account/signup.html')
    else:
        return redirect('main:index_page')


def signout(request):
    if request.user.is_authenticated:
        logout(request)
        return redirect('main:index_page')
    else:
        return redirect('main:index_page')


def signin(request):
    response_data = {}
    try:
        username = request.POST.get('username')
        password = request.POST.get('password')
        remember_me = json.loads(request.POST.get('remember_me'))
        # get this user
        user = authenticate(request, username = username, password = password)
        # check user
        if user is not None:
            # login user
            login(request, user)
            if remember_me:
                session_key = request.session.session_key or Session.objects.get_new_session_key()
                Session.objects.save(session_key, request.session._session, timezone.now() + datetime.timedelta(seconds = settings.SESSION_COOKIE_AGE))

            response_data['status'] = '200'
            return JsonResponse(response_data)
        else:
            response_data['status'] = '404'
            response_data['error'] = 'نام کاربری یا رمز عبور اشتباه است و یا حساب کاربری شما غیر فعال شده است.'
            return JsonResponse(response_data)
    except Exception as e:
        response_data['status'] = '500'
        response_data['error'] = str(e)
        return JsonResponse(response_data)


def forget_password_page(request):
    if not request.user.is_authenticated:
        return render(request, 'account/forget-password.html')
    else:
        return redirect('main:index_page')


def forget_password_send_validation_code(request):
    response_data = {}
    try:
        if not request.user.is_authenticated:
            # get data
            this_mobile = request.POST.get('mobile')
            # check mobile
            if User.objects.filter(mobile = this_mobile).exists():
                this_user = User.objects.get(mobile = this_mobile)
                # check mobile in Validation Model
                if Validation.objects.filter(mobile = this_mobile).exists():
                    this_validation = Validation.objects.get(mobile = this_mobile)
                    # check send time
                    start = timezone.localtime(this_validation.createdatetime)
                    end = timezone.localtime(timezone.now())
                    delta_time = calculate_time_difference(start, end)
                    if delta_time <= 120:
                        response_data['status'] = '400'
                        response_data['error'] = 'کد ارسال شده برای شما هنوز معتبر می باشد.'
                        return JsonResponse(response_data)
                    else:
                        this_validation.validation_code = ''.join(random.choice(string.digits) for i in range(6))
                        this_validation.createdatetime = timezone.now()
                        this_validation.save()
                        status, error = send_sms(this_mobile, 'hse-verify-code', str(this_validation.validation_code))
                        response_data['status'] = '200'
                        response_data['send_sms_status'] = {'status': status, 'error': error}
                        response_data['user_id'] = this_user.id
                        return JsonResponse(response_data)
                else:
                    this_validation = Validation.objects.create(mobile = this_mobile)
                    status, error = send_sms(this_mobile, 'hse-verify-code', str(this_validation.validation_code))
                    response_data['status'] = '201'
                    response_data['send_sms_status'] = {'status': status, 'error': error}
                    response_data['user_id'] = this_user.id
                    return JsonResponse(response_data)
            else:
                response_data['status'] = '404'
                response_data['error'] = 'کاربری با این شماره موبایل در سیستم موجود نمی باشد.'
                return JsonResponse(response_data)
        else:
            response_data['status'] = '400'
            response_data['error'] = 'شما در حال حاضر نمی توانید از فراموشی رمز عبور استفاده کنید.'
            return JsonResponse(response_data)
    except Exception as e:
        response_data['status'] = '500'
        response_data['error'] = str(e)
        return JsonResponse(response_data)


def forget_password_change_password(request):
    response_data = {}
    try:
        if not request.user.is_authenticated:
            # get data
            this_user_id = request.POST.get('user_id')
            this_validation_code = request.POST.get('validation_code')
            this_password = request.POST.get('password')
            this_re_password = request.POST.get('re_password')
            # set data
            this_user = User.objects.get(id = this_user_id)
            # check mobile
            if Validation.objects.filter(mobile = this_user.mobile).exists():
                this_validation = Validation.objects.get(mobile = this_user.mobile)
                # check send time
                start = timezone.localtime(this_validation.createdatetime)
                end = timezone.localtime(timezone.now())
                delta_time = calculate_time_difference(start, end)
                if delta_time > 120:
                    response_data['status'] = '406'
                    response_data['error'] = 'کد وارد شده، منقضی شده است.'
                    return JsonResponse(response_data)
                # check validation code
                if this_validation.validation_code == this_validation_code:
                    password_status, error = check_password(this_password, this_re_password)
                    if not password_status:
                        response_data['status'] = '400'
                        response_data['error'] = error
                        return JsonResponse(response_data)
                    # change password
                    this_user.set_password(this_password)
                    this_user.save()
                    
                    response_data['status'] = '200'
                    return JsonResponse(response_data)
                else:
                    response_data['status'] = '406'
                    response_data['error'] = 'کد وارد شده درست نمی باشد.'
                    return JsonResponse(response_data)
            else:
                response_data['status'] = '404'
                response_data['error'] = 'کدی برای این کاربر ارسال نشده است.'
                return JsonResponse(response_data)
        else:
            response_data['status'] = '400'
            response_data['error'] = 'شما در حال حاضر نمی توانید از فراموشی رمز عبور استفاده کنید.'
            return JsonResponse(response_data)
    except Exception as e:
        response_data['status'] = '500'
        response_data['error'] = str(e)
        return JsonResponse(response_data)


def check_signup_fields(request):
    try:
        # get data
        this_username = request.POST.get('username')
        this_password = request.POST.get('password')
        this_first_name = request.POST.get('first_name')
        this_last_name = request.POST.get('last_name')
        this_father_s_name = request.POST.get('father_s_name')
        this_gender = request.POST.get('gender')
        this_birth_certificate_id = request.POST.get('birth_certificate_id')
        this_national_code = request.POST.get('national_code')
        this_birthday = request.POST.get('birthday')
        this_issue_place = request.POST.get('issue_place')
        this_degree = request.POST.get('degree')
        this_major = request.POST.get('major')
        this_university_of_study = request.POST.get('university_of_study')
        this_executive_device = request.POST.get('executive_device')
        this_role = request.POST.get('role')
        this_work_experience = request.POST.get('work_experience')
        this_personnel_id = request.POST.get('personnel_id')
        this_address = request.POST.get('address')
        this_zip_code = request.POST.get('zip_code')
        this_mobile = request.POST.get('mobile')
        this_necessary_contact_number = request.POST.get('necessary_contact_number')
        this_workplace_number = request.POST.get('workplace_number')
        this_email = request.POST.get('email')
        this_profile = request.FILES['profile']
        this_picture = request.FILES['picture']
        this_personal_id_card = request.FILES['personal_id_card']
        this_device_introduction_letter = request.FILES['device_introduction_letter']
        this_sample_signature = request.FILES['sample_signature']
        # check duplicate data
        if User.objects.filter(username = this_username).exists():
            return False, 'کاربری با این نام کاربری در سیستم موجود می باشد.'
        if User.objects.filter(birth_certificate_id = this_birth_certificate_id).exists():

templates/main/communication/communication-create.html
{% load i18n static %}
{% csrf_token %}

{% block head %}
    {% include "parents/head.html" %}
{% endblock %}

<title>سامانه پروژه ها | ایجاد یک نامه مکاتباتی   </title>
</head>

<body>
    <div class="loading-fixed d-hide">
        <img src="{% static "images/loading.svg" %}" alt="در حال بارگذاری...">
    </div>

    {% block header %}
        {% include "parents/header.html" %}
    {% endblock %}

    <div class="container-fluid">
        <div class="row">

            {% block sidebar %}
                {% include "parents/sidebar.html" %}
            {% endblock %}

            <div class="col-9">
                <div class="row text-right">
                    <div class="col-12">
                        <div class="blur">
                            <h2 class="title_page">ثبت یک نامه مکاتباتی</h2>
                            <div class="row">
                                <div class="col-12">
                                    <div class="alert-section">
                                        <div class="alert-message error-message front text-right mb-3">
                                            <div class="alert-message-content error-content">
                                                <i class="fas fa-exclamation-circle"></i>
                                                <div class="alert-message-text error-text">
                                                </div>
                                            </div>
                                            <div class="close-message close-error-message">
                                                <i class="fas fa-times"></i>
                                            </div>
                                        </div>
                                        <div class="alert-message success-message front text-right mb-3">
                                            <div class="alert-message-content success-content">
                                                <i class="fas fa-check"></i>
                                                <div class="alert-message-text success-text">
                                                     نامه مکاتباتی جدید با موفقیت ثبت گردید.
                                                </div>
                                            </div>
                                            <div class="close-message close-success-message">
                                                <i class="fas fa-times"></i>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <form>
                                <div class="form-row">
                                    <div class="form-group col-md-4">
                                        <label for="inputCommunicationTitle">عنوان نامه مکاتباتی<code>*</code></label>
                                        <i class="fal fa-info-circle tooltip-arrow" data-toggle="tooltip"
                                            data-placement="left"
                                            title="عنوان نامه مکاتباتی نباید خالی باشد و باید حداکثر تا 255 کاراکتر طول داشته باشد."></i>
                                        <input type="text" class="form-control" id="inputCommunicationTitle" placeholder=""
                                            maxlength="255">
                                    </div>
                                </div>
                                

                                <div class="form-row">
                                    <div class="form-group col-md-12">
                                      <label for="inputDescription">توضیحات<code>*</code></label>
                                      <textarea class="form-control" id="inputDescription" rows="4"></textarea>
                                    </div>
                                </div>
                                <div class="form-row">
                                    <label for="inputFile">پیوست</label>
                                    <input type="file" class="form-control-file" id="inputFile">
                                </div>
                                <br>

                                <div class="form-row">
                                    <div class="form-group col-md-4">
                                        <label for="inputToUser">ارجاع به<code>*</code></label>
                                        <i class="fal fa-info-circle tooltip-arrow" data-toggle="tooltip"
                                            data-placement="left" title="تعیین فرد الزامی میباشد."></i>
                                        <select id="inputToUser" class="form-control select2-ajax-user">
                                        </select>
                                      </div>
                                </div>

                                <button id="submit" type="submit" class="btn btn-primary">ثبت</button>
                                <br>
                                <br>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {% block footer %}
    {% include "parents/footer.html" %}
    {% endblock %}

    <script src="{% static "js/base-information/communication.js" %}" type="text/javascript"></script>

    <script>

        $(".select2-ajax-user").select2({
            dir: "rtl",
            ajax: {
                method: 'POST',
                url: "{% url 'master_data:ajax_search_in_users' %}",
                dataType: 'json',
                delay: 250,
                data: function (params) {
                    return {
                        search: params.term, // search term
                        csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val(),
                    };
                },
                processResults: function (data, params) {
                    params.page = params.page || 1;

                    return {
                        results: data.data,
                        pagination: {
                            more: (params.page * 30) < data.total_count
                        }
                    };
                },
                cache: true
            },
            width: '100%',
            placeholder: 'جستجو...',
            minimumInputLength: 1,
            templateResult: formatRepo,
            templateSelection: formatRepoSelection
        });

        function formatRepo(repo) {
            if (repo.loading) {
                return repo.text;
            }

            var $container = $(
                "<div class='select2-result-repository clearfix'>" +
                "<div class='select2-result-repository__meta'>" +
                "<div class='select2-result-repository__title'></div>" +
                "</div>" +
                "</div>"
            );

            $container.find(".select2-result-repository__title").text(repo.first_name + ' ' + repo.last_name + ' (' + repo.national_code + ')');

            return $container;
        }

        function formatRepoSelection(repo) {
            if (repo.first_name && repo.last_name && repo.national_code) {
                return repo.first_name + ' ' + repo.last_name + ' (' + repo.national_code + ')';
            }
            return repo.text;
        }

        $("#submit").click(function (e) {
            e.preventDefault();
            var checks = checkCommunicationFnc();
            if (checks) {
                $(".blur").addClass('active disable-form');
                $(".loading-fixed").show();

                var formData = new FormData();

                var title = $("#inputCommunicationTitle").val();
                var description = $("#inputDescription").val();
                var file = $("#inputFile")[0].files[0];
                var referToUser = $("#inputToUser").val();

                formData.append('title', title);                
                formData.append('description', description);                
                formData.append('attached_file', file);                
                formData.append('receiver_id', referToUser);                
                
                var csrftoken = $("input[name=csrfmiddlewaretoken]").val();
                
                $.ajax(
                    {
                        method: 'POST',
                        url: '{% url "main:ajax_create_official_letter" %}',
                        headers: {
                            'X-CSRFToken': csrftoken
                        },
                        contentType: false,
                        processData: false,
                        data: formData,
                        success: function (json) {
                            if (json.status == '201') {
                                $(".blur").removeClass('active');
                                $(".loading-fixed").hide();
                                $("html, body").animate({
                                    scrollTop: $(".alert-section").offset().top - 20
                                }, 1000);
                                $(".alert-message.success-message").show();
                                $(".alert-message.error-message").hide();
                                var redirectURL = '{% url "main:communication_list_page" %}';
                                setTimeout(function () {
                                    location.replace(redirectURL);
                                }, 1500)
                            }
                            else {
                                $(".blur").removeClass('active disable-form');
                                $(".loading-fixed").hide();
                                $("html, body").animate({
                                    scrollTop: $(".alert-section").offset().top - 20
                                }, 1000);
                                $(".alert-message-text.error-text").html(json.error + ' ' + '(' + json.status + ')');
                                $(".alert-message.error-message").show();
                            }
                        },
                        error: function (json, status, xhr) {
                            console.log(json);
                            console.log(status);
                            console.log(xhr);
                            $(".blur").removeClass('active disable-form');
                            $(".loading-fixed").hide();
                            $("html, body").animate({
                                scrollTop: $(".alert-section").offset().top - 20
                            }, 1000);
                            $(".alert-message-text.error-text").html(xhr + ' ' + '(' + status + ')');
                            $(".alert-message.error-message").show();
                        }
                    }
                )
            }
            else {
                $("html, body").animate({
                    scrollTop: $(".alert-section").offset().top - 20
                }, 1000);
            }
        })
    </script>

</body>

</html>